name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.22

      - name: Prepare Project
        run: |
          bun install --frozen-lockfile
          cp .env.example .env
          bun --bun x svelte-kit sync

      - name: Svelte Check
        run: bun --bun x svelte-check

      - name: Build
        run: bun --bun x vite build

      - name: Prepare Artifacts
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./build

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
